directories:
  output: dist-electron
  buildResources: build
appId: com.aritmo.app
productName: Aritmo
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  icon: resources/favicon.ico
  target:
    - nsis
mac:
  icon: resources/logo512.png
linux:
  icon: resources/logo512.png
electronVersion: 39.2.6
